# Generated by Django 4.1 on 2022-08-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item", name="text", field=models.TextField(default=""),
        ),
    ]
